services:
  backend:
    build: ./php
    container_name: currencyconverter-backend
    expose:
      - 9000
    volumes:
      - ./php:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: currencyconverter-nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - backend